# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/apko/refs/heads/main/pkg/build/types/schema.json
include: bootc.yaml
contents:
  packages:
    - pinewall-config=0.0.2-r1
    - avahi
    - bind-tools
    - blocky
    - conntrack-tools
    - curl
    - dnsmasq
    - ethtool
    - htop
    - iftop
    - iperf3
    - nftables
    - openssh
    - openssh-server-config
    - openssh-service
    - openssl
    - prometheus-node-exporter
    - tailscale
    - tcpdump
