name: GHCR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    name: GHCR Cleanup
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: cleanup
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1
        with:
          packages: '*'
          expand-packages: true
          keep-n-tagged: 32
          keep-n-untagged: 8
          token: ${{ secrets.CLEANUP_PAT }}
